[Unit]
Requires=systemd-tmpfiles-setup.service
After=systemd-tmpfiles-setup.service inputplumber.service
Requires=pocketds-controller-test.service
After=pocketds-controller-test.service

[Service]
ReadWritePaths=/run/pocketds-input-mode
ExecStartPre=/usr/local/libexec/pocketds-input-mode bootstrap
