[main]
summary=Pocket DS quiet battery-saving profile

[cpu]
governor=schedutil

[sysfs]
/sys/devices/system/cpu/cpufreq/policy0/scaling_min_freq=307200
/sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq=1670400
/sys/devices/system/cpu/cpufreq/policy3/scaling_min_freq=499200
/sys/devices/system/cpu/cpufreq/policy3/scaling_max_freq=2188800
/sys/devices/system/cpu/cpufreq/policy7/scaling_min_freq=595200
/sys/devices/system/cpu/cpufreq/policy7/scaling_max_freq=2476800
/sys/class/devfreq/3d00000.gpu/min_freq=220000000
/sys/class/devfreq/3d00000.gpu/max_freq=550000000
/sys/class/devfreq/3d00000.gpu/governor=simple_ondemand

[script]
script=${i:PROFILE_DIR}/fan-profile.sh
